[INFO] 2018-04-24 11:17:14 : buy by limit
[INFO] 2018-04-25 22:23:14 : buy by limit
[INFO] 2018-04-25 22:39:00 : Balance:7975.022204975
[INFO] 2018-04-25 22:39:00 : highest:9214.5
[INFO] 2018-04-25 22:39:00 : lowest:9207
[INFO] 2018-04-25 22:39:00 : high:9204.5
[INFO] 2018-04-25 22:39:00 : low:9204.5

[INFO] 2018-04-25 22:39:00 : Sell!!
[INFO] 2018-04-25 22:39:06 : sell by limit
[INFO] 2018-04-25 22:39:06 : Came back to loop!!
[INFO] 2018-04-25 22:39:07 : highest:9214.5
[INFO] 2018-04-25 22:39:07 : lowest:9207
[INFO] 2018-04-25 22:39:07 : high:9204.5
[INFO] 2018-04-25 22:39:07 : low:9204.5

[INFO] 2018-04-25 22:39:37 : highest:9214.5
[INFO] 2018-04-25 22:39:37 : lowest:9207
[INFO] 2018-04-25 22:39:37 : high:9204.5
[INFO] 2018-04-25 22:39:37 : low:9204.5

[INFO] 2018-04-25 22:40:08 : highest:9214.5
[INFO] 2018-04-25 22:40:08 : lowest:9207
[INFO] 2018-04-25 22:40:08 : high:9204.5
[INFO] 2018-04-25 22:40:08 : low:9204.5

[INFO] 2018-04-25 22:40:38 : highest:9214.5
[INFO] 2018-04-25 22:40:38 : lowest:9207
[INFO] 2018-04-25 22:40:39 : high:9204.5
[INFO] 2018-04-25 22:40:39 : low:9204.5

[INFO] 2018-04-25 22:41:09 : highest:9214.5
[INFO] 2018-04-25 22:41:09 : lowest:9207
[INFO] 2018-04-25 22:41:09 : high:9204.5
[INFO] 2018-04-25 22:41:09 : low:9204.5

[INFO] 2018-04-25 22:41:39 : highest:9214.5
[INFO] 2018-04-25 22:41:39 : lowest:9207
[INFO] 2018-04-25 22:41:40 : high:9204.5
[INFO] 2018-04-25 22:41:40 : low:9204.5

[INFO] 2018-04-25 22:42:10 : highest:9211.5
[INFO] 2018-04-25 22:42:10 : lowest:9204.5
[INFO] 2018-04-25 22:42:10 : high:9195.5
[INFO] 2018-04-25 22:42:10 : low:9195.5

[INFO] 2018-04-25 22:42:40 : highest:9211.5
[INFO] 2018-04-25 22:42:40 : lowest:9204.5
[INFO] 2018-04-25 22:42:41 : high:9195.5
[INFO] 2018-04-25 22:42:41 : low:9195.5

[INFO] 2018-04-25 22:43:11 : highest:9211.5
[INFO] 2018-04-25 22:43:11 : lowest:9204.5
[INFO] 2018-04-25 22:43:11 : high:9195.5
[INFO] 2018-04-25 22:43:11 : low:9195.5

[INFO] 2018-04-25 22:43:42 : highest:9211.5
[INFO] 2018-04-25 22:43:42 : lowest:9204.5
[INFO] 2018-04-25 22:43:42 : high:9195.5
[INFO] 2018-04-25 22:43:42 : low:9195.5

[INFO] 2018-04-25 22:44:12 : highest:9211.5
[INFO] 2018-04-25 22:44:12 : lowest:9204.5
[INFO] 2018-04-25 22:44:12 : high:9195.5
[INFO] 2018-04-25 22:44:12 : low:9195.5

[INFO] 2018-04-25 22:44:43 : highest:9211.5
[INFO] 2018-04-25 22:44:43 : lowest:9204.5
[INFO] 2018-04-25 22:44:43 : high:9195.5
[INFO] 2018-04-25 22:44:43 : low:9195.5

[INFO] 2018-04-25 22:45:13 : highest:9208
[INFO] 2018-04-25 22:45:13 : lowest:9195.5
[INFO] 2018-04-25 22:45:13 : high:9194.5
[INFO] 2018-04-25 22:45:13 : low:9194.5

[INFO] 2018-04-25 22:45:44 : highest:9208
[INFO] 2018-04-25 22:45:44 : lowest:9195.5
[INFO] 2018-04-25 22:45:44 : high:9194.5
[INFO] 2018-04-25 22:45:44 : low:9194.5

[INFO] 2018-04-25 22:46:14 : highest:9208
[INFO] 2018-04-25 22:46:14 : lowest:9195.5
[INFO] 2018-04-25 22:46:14 : high:9194.5
[INFO] 2018-04-25 22:46:14 : low:9194.5

[INFO] 2018-04-25 22:46:45 : highest:9208
[INFO] 2018-04-25 22:46:45 : lowest:9195.5
[INFO] 2018-04-25 22:46:45 : high:9194.5
[INFO] 2018-04-25 22:46:45 : low:9194.5

[INFO] 2018-04-25 22:47:15 : highest:9208
[INFO] 2018-04-25 22:47:15 : lowest:9195.5
[INFO] 2018-04-25 22:47:16 : high:9194.5
[INFO] 2018-04-25 22:47:16 : low:9194.5

[INFO] 2018-04-25 22:47:46 : highest:9208
[INFO] 2018-04-25 22:47:46 : lowest:9195.5
[INFO] 2018-04-25 22:47:46 : high:9194.5
[INFO] 2018-04-25 22:47:46 : low:9194.5

[INFO] 2018-04-25 22:48:16 : highest:9208
[INFO] 2018-04-25 22:48:16 : lowest:9194.5
[INFO] 2018-04-25 22:48:17 : high:9172
[INFO] 2018-04-25 22:48:17 : low:9172

[INFO] 2018-04-25 22:48:47 : highest:9208
[INFO] 2018-04-25 22:48:47 : lowest:9194.5
[INFO] 2018-04-25 22:48:47 : high:9172
[INFO] 2018-04-25 22:48:47 : low:9172

[INFO] 2018-04-25 22:49:17 : highest:9208
[INFO] 2018-04-25 22:49:17 : lowest:9194.5
[INFO] 2018-04-25 22:49:18 : high:9172
[INFO] 2018-04-25 22:49:18 : low:9172

[INFO] 2018-04-25 22:49:48 : highest:9208
[INFO] 2018-04-25 22:49:48 : lowest:9194.5
[INFO] 2018-04-25 22:49:48 : high:9172
[INFO] 2018-04-25 22:49:48 : low:9172

[INFO] 2018-04-25 22:50:18 : highest:9208
[INFO] 2018-04-25 22:50:18 : lowest:9194.5
[INFO] 2018-04-25 22:50:19 : high:9172
[INFO] 2018-04-25 22:50:19 : low:9172

[INFO] 2018-04-25 22:50:49 : highest:9208
[INFO] 2018-04-25 22:50:49 : lowest:9194.5
[INFO] 2018-04-25 22:50:49 : high:9172
[INFO] 2018-04-25 22:50:49 : low:9172

[INFO] 2018-04-25 22:51:20 : highest:9204.5
[INFO] 2018-04-25 22:51:20 : lowest:9172
[INFO] 2018-04-25 22:51:20 : high:9183
[INFO] 2018-04-25 22:51:20 : low:9183

[INFO] 2018-04-25 22:51:50 : highest:9204.5
[INFO] 2018-04-25 22:51:50 : lowest:9172
[INFO] 2018-04-25 22:51:50 : high:9183
[INFO] 2018-04-25 22:51:50 : low:9183

[INFO] 2018-04-25 22:52:21 : highest:9204.5
[INFO] 2018-04-25 22:52:21 : lowest:9172
[INFO] 2018-04-25 22:52:21 : high:9183
[INFO] 2018-04-25 22:52:21 : low:9183

[INFO] 2018-04-25 22:52:51 : highest:9204.5
[INFO] 2018-04-25 22:52:51 : lowest:9172
[INFO] 2018-04-25 22:52:51 : high:9183
[INFO] 2018-04-25 22:52:51 : low:9183

[INFO] 2018-04-25 22:53:22 : highest:9204.5
[INFO] 2018-04-25 22:53:22 : lowest:9172
[INFO] 2018-04-25 22:53:22 : high:9183
[INFO] 2018-04-25 22:53:22 : low:9183

[INFO] 2018-04-25 22:53:52 : highest:9204.5
[INFO] 2018-04-25 22:53:52 : lowest:9172
[INFO] 2018-04-25 22:53:53 : high:9183
[INFO] 2018-04-25 22:53:53 : low:9183

[INFO] 2018-04-25 22:54:23 : highest:9195.5
[INFO] 2018-04-25 22:54:23 : lowest:9172
[INFO] 2018-04-25 22:54:23 : high:9184
[INFO] 2018-04-25 22:54:23 : low:9184

[INFO] 2018-04-25 22:54:53 : highest:9195.5
[INFO] 2018-04-25 22:54:53 : lowest:9172
[INFO] 2018-04-25 22:54:54 : high:9184
[INFO] 2018-04-25 22:54:54 : low:9184

[INFO] 2018-04-25 22:55:24 : highest:9195.5
[INFO] 2018-04-25 22:55:24 : lowest:9172
[INFO] 2018-04-25 22:55:24 : high:9184
[INFO] 2018-04-25 22:55:24 : low:9184

[INFO] 2018-04-25 22:55:54 : highest:9195.5
[INFO] 2018-04-25 22:55:54 : lowest:9172
[INFO] 2018-04-25 22:55:55 : high:9184
[INFO] 2018-04-25 22:55:55 : low:9184

[INFO] 2018-04-25 22:56:25 : highest:9195.5
[INFO] 2018-04-25 22:56:25 : lowest:9172
[INFO] 2018-04-25 22:56:25 : high:9184
[INFO] 2018-04-25 22:56:25 : low:9184

[INFO] 2018-04-25 22:56:56 : highest:9195.5
[INFO] 2018-04-25 22:56:56 : lowest:9172
[INFO] 2018-04-25 22:56:56 : high:9184
[INFO] 2018-04-25 22:56:56 : low:9184

[INFO] 2018-04-25 22:57:26 : highest:9194.5
[INFO] 2018-04-25 22:57:26 : lowest:9172
[INFO] 2018-04-25 22:57:26 : high:9166
[INFO] 2018-04-25 22:57:26 : low:9166

[INFO] 2018-04-25 22:57:57 : highest:9194.5
[INFO] 2018-04-25 22:57:57 : lowest:9172
[INFO] 2018-04-25 22:57:57 : high:9166
[INFO] 2018-04-25 22:57:57 : low:9166

[INFO] 2018-04-25 22:58:27 : highest:9194.5
[INFO] 2018-04-25 22:58:27 : lowest:9172
[INFO] 2018-04-25 22:58:27 : high:9166
[INFO] 2018-04-25 22:58:27 : low:9166

[INFO] 2018-04-25 22:58:58 : highest:9194.5
[INFO] 2018-04-25 22:58:58 : lowest:9172
[INFO] 2018-04-25 22:58:58 : high:9166
[INFO] 2018-04-25 22:58:58 : low:9166

[INFO] 2018-04-25 22:59:28 : highest:9194.5
[INFO] 2018-04-25 22:59:28 : lowest:9172
[INFO] 2018-04-25 22:59:28 : high:9166
[INFO] 2018-04-25 22:59:28 : low:9166

[INFO] 2018-04-25 22:59:59 : highest:9194.5
[INFO] 2018-04-25 22:59:59 : lowest:9172
[INFO] 2018-04-25 22:59:59 : high:9166
[INFO] 2018-04-25 22:59:59 : low:9166

[INFO] 2018-04-25 23:00:29 : highest:9184
[INFO] 2018-04-25 23:00:29 : lowest:9166
[INFO] 2018-04-25 23:00:30 : high:9160
[INFO] 2018-04-25 23:00:30 : low:9160

[INFO] 2018-04-25 23:01:00 : highest:9184
[INFO] 2018-04-25 23:01:00 : lowest:9166
[INFO] 2018-04-25 23:01:00 : high:9160
[INFO] 2018-04-25 23:01:00 : low:9160

[INFO] 2018-04-25 23:01:30 : highest:9184
[INFO] 2018-04-25 23:01:30 : lowest:9166
[INFO] 2018-04-25 23:01:31 : high:9160
[INFO] 2018-04-25 23:01:31 : low:9160

[INFO] 2018-04-25 23:02:01 : highest:9184
[INFO] 2018-04-25 23:02:01 : lowest:9166
[INFO] 2018-04-25 23:02:01 : high:9160
[INFO] 2018-04-25 23:02:01 : low:9160

[INFO] 2018-04-25 23:02:31 : highest:9184
[INFO] 2018-04-25 23:02:31 : lowest:9166
[INFO] 2018-04-25 23:02:32 : high:9160
[INFO] 2018-04-25 23:02:32 : low:9160

[INFO] 2018-04-25 23:03:02 : highest:9184
[INFO] 2018-04-25 23:03:02 : lowest:9160
[INFO] 2018-04-25 23:03:02 : high:9139
[INFO] 2018-04-25 23:03:02 : low:9139

[INFO] 2018-04-25 23:03:33 : highest:9184
[INFO] 2018-04-25 23:03:33 : lowest:9160
[INFO] 2018-04-25 23:03:33 : high:9139
[INFO] 2018-04-25 23:03:33 : low:9139

[INFO] 2018-04-25 23:04:03 : highest:9184
[INFO] 2018-04-25 23:04:03 : lowest:9160
[INFO] 2018-04-25 23:04:03 : high:9139
[INFO] 2018-04-25 23:04:03 : low:9139

[INFO] 2018-04-25 23:04:34 : highest:9184
[INFO] 2018-04-25 23:04:34 : lowest:9160
[INFO] 2018-04-25 23:04:34 : high:9139
[INFO] 2018-04-25 23:04:34 : low:9139

[INFO] 2018-04-25 23:05:04 : highest:9184
[INFO] 2018-04-25 23:05:04 : lowest:9160
[INFO] 2018-04-25 23:05:04 : high:9139
[INFO] 2018-04-25 23:05:04 : low:9139

[ERROR] 2018-04-25 23:05:44 : 例外が発生しました。RequestTimeout("bitmex GET https://testnet.bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1m&partial=True&startTime=2018-04-25+13%3A47 HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Read timed out. (read timeout=10)",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 350, in fetch
    proxies=self.proxies
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trade.py", line 121, in channel_break
    product_code, candle_term, past_time)
  File "trade.py", line 174, in fetch_original_ohlcv
    product_code, timeframe=candle_term, since=since)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ccxt/bitmex.py", line 347, in fetch_ohlcv
    response = self.publicGetTradeBucketed(self.extend(request, params))
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 299, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 296, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 360, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "/mnt/c/Users/author/Ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 281, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: bitmex GET https://testnet.bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1m&partial=True&startTime=2018-04-25+13%3A47 HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Read timed out. (read timeout=10)
[INFO] 2018-04-25 23:06:12 : highest:9184
[INFO] 2018-04-25 23:06:12 : lowest:9160
[INFO] 2018-04-25 23:06:12 : high:9139
[INFO] 2018-04-25 23:06:12 : low:9139

[ERROR] 2018-04-27 21:32:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:32:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:32:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:32:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:32:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:32:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:42 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:42 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:42 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:42 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:42 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:42 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:34:52 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:35:02 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:35:12 : 例外が発生しました。NameError("name 'fetch_original_ohlcv' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 86, in channel_break
    multi_candles = fetch_original_ohlcv(
NameError: name 'fetch_original_ohlcv' is not defined
[ERROR] 2018-04-27 21:35:18 : 例外が発生しました。NameError("name 'product_code' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 87, in channel_break
    product_code, candle_term, past_time)
NameError: name 'product_code' is not defined
[ERROR] 2018-04-27 21:35:18 : 例外が発生しました。NameError("name 'product_code' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 87, in channel_break
    product_code, candle_term, past_time)
NameError: name 'product_code' is not defined
[ERROR] 2018-04-27 21:35:18 : 例外が発生しました。NameError("name 'product_code' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 87, in channel_break
    product_code, candle_term, past_time)
NameError: name 'product_code' is not defined
[ERROR] 2018-04-27 21:35:18 : 例外が発生しました。NameError("name 'product_code' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 87, in channel_break
    product_code, candle_term, past_time)
NameError: name 'product_code' is not defined
[ERROR] 2018-04-27 21:35:18 : 例外が発生しました。NameError("name 'product_code' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 87, in channel_break
    product_code, candle_term, past_time)
NameError: name 'product_code' is not defined
[ERROR] 2018-04-27 21:35:18 : 例外が発生しました。NameError("name 'product_code' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 87, in channel_break
    product_code, candle_term, past_time)
NameError: name 'product_code' is not defined
[ERROR] 2018-04-27 21:39:22 : 例外が発生しました。NameError("name 'logger' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 93, in channel_break
    logger.info('highest:{}'.format(highest))
NameError: name 'logger' is not defined
[ERROR] 2018-04-27 21:39:23 : 例外が発生しました。NameError("name 'logger' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 93, in channel_break
    logger.info('highest:{}'.format(highest))
NameError: name 'logger' is not defined
[ERROR] 2018-04-27 21:39:23 : 例外が発生しました。NameError("name 'logger' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 93, in channel_break
    logger.info('highest:{}'.format(highest))
NameError: name 'logger' is not defined
[ERROR] 2018-04-27 21:39:23 : 例外が発生しました。NameError("name 'logger' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 93, in channel_break
    logger.info('highest:{}'.format(highest))
NameError: name 'logger' is not defined
[ERROR] 2018-04-27 21:39:23 : 例外が発生しました。NameError("name 'logger' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 93, in channel_break
    logger.info('highest:{}'.format(highest))
NameError: name 'logger' is not defined
[ERROR] 2018-04-27 21:39:24 : 例外が発生しました。NameError("name 'logger' is not defined",)
Traceback (most recent call last):
  File "/mnt/c/Users/author/Ubuntu/auto-trade/test/ChannelBreak/src/logic.py", line 93, in channel_break
    logger.info('highest:{}'.format(highest))
NameError: name 'logger' is not defined
[INFO] 2018-04-27 21:40:38 : highest:9228.5
[INFO] 2018-04-27 21:40:38 : lowest:9209.5
[INFO] 2018-04-27 21:40:38 : high:9212.5
[INFO] 2018-04-27 21:40:38 : low:9210

